---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**
      - src/strategies
      - src/strategies-meta
  push:
    paths:
      - '**.h'
      - '**.mq?'
      - .github/workflows/test.yml
      - src/*.mq?
      - src/*.mq[45h]
      - src/include/**
      - src/strategies
      - src/strategies-meta

env:
  INDI_COMMON_WORKDIR: ${{ vars.INDI_COMMON_WORKDIR || 'src/indicators/Common' }}
  INDI_OTHER_WORKDIR: ${{ vars.INDI_OTHER_WORKDIR || 'src/indicators/Other' }}

jobs:

  compile-ea:
    name: Compile EA
    uses: ./.github/workflows/compile.yml
    with:
      skip_cleanup: true

  test:

    defaults:
      run:
        shell: bash

    name: Test
    needs: compile-ea
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mode:
          - Lite
          - Advanced
          - Elite
          - Rider
        year: [2022, 2024]
        version: [5]
      max-parallel: 4

    steps:

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          name: EA31337-${{ matrix.mode }}(__resource__)-ex${{ matrix.version }}

      - name: List compiled files
        run: find . -name '*.ex?' -type f -print

      - name: Test ${{ matrix.year }}
        uses: fx31337/mql-tester-action@master
        with:
          Login: ${{ secrets.MT5_LOGIN }}
          Password: ${{ secrets.MT5_PASSWORD }}
          Server: MetaQuotes-Demo
          TestDeposit: 2000
          TestExpert: EA31337-${{ matrix.mode }}-${{ github.sha }}
          TestFromDate: ${{ matrix.year }}.01.01
          TestPeriod: M1
          TestSymbol: EURUSD
          TestToDate: ${{ matrix.year }}.01.14
          # yamllint disable-line rule:line-length
          UrlExpert: >-
            file://${{ github.workspace }}/EA31337-${{ matrix.mode }}-${{ github.sha }}.ex${{ matrix.version }}
          Version: 5

      - if: ${{ failure() && runner.debug == '1' }}
        uses: mxschmitt/action-tmate@v3

    timeout-minutes: 30

  cleanup:
    if: inputs.skip_cleanup != true
    name: Clean-up
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            ic[45]
            io[45]
    timeout-minutes: 5
